DjangoProject/urls.py
from django.contrib import admin
from django.urls import path , include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/',include("hello.urls")),
     path('todolist/',include("todolist.urls")),
    path('newyear/', include("newyear.urls"))
    
]

hello/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.index, name = "index" ),
    path("Tomasa",views.Tomasa, name ="Tomasa" ),
    path("Daniel",views.Daniel, name = "Daniel"),    
    path("<str:name>", views.greet, name = "greet")
]

newyear/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.index, name = "index" ),
    ]

todolist/urls.py
from django.urls import path
from . import views

app_name = "todolist"
urlpatterns = [
    path("", views.index, name = "index" ),
    path("add",views.add, name="add")
    ]

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

todolist/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"hello/index.html")
    #return HttpResponse("Hello, Alejandro Hidalgo Badillo!")

def Tomasa(request):
    return HttpResponse("Hello, Tomasa!")

def Daniel(request):
    return HttpResponse("Hello, Daniel Hidalgo!")

def greet(request, name):
    #return HttpResponse(f"hello! {name.capitalize()}")
    return render(request,"hello/greet.html", {
        "name": name.capitalize()
    })

newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.

def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

todolist/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
#todolist =[]

class NewTaskForm(forms.Form):  
    task = forms.CharField(label="New Task")
    #priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)


# Create your views here.
def index(request):
    if "todolist" not in request.session:
        request.session["todolist"] = []
    return render(request, "todolist/index.html",{
        "todolist": request.session["todolist"] 
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["todolist"] += [task]
            return HttpResponseRedirect(reverse("todolist:index"))
        else:
            return render(request,"todolist/add.html",{
                "form": form
            })

    return render(request, "todolist/add.html", {
        "form":NewTaskForm()
    })

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">

    
    <head> 
        <title>Hello!</title>
    </head>

    <body>
        <h1>Hello, {{ name }} !</h1>
    </body>
    
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">

    
    <head> 
        <title>Hello!</title>
    </head>

    <body>
        <h1>Hello,  world!</h1>
    </body>
    
</html>

newyear/templates/newyear/index.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
    
    <head>
        <title>Is it new Year´s? </title>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet"> 
    </head>
  
    <body>
        {%  if newyear    %}
            <h1>YES</h1>
        {%  else  %}
            <h1>NO</h1>
        {% endif %}
    </body>
    

</html>

todolist/templates/todolist/add.html
{% extends "todolist/layout.html" %}

{% block body %}
        <h1>Add task</h1>    
        <form action = "{% url 'todolist:add' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
        <a href="{% url 'todolist:index' %}"> View Tasks</a>
{% endblock %}

todolist/templates/todolist/index.html
{% extends "todolist/layout.html" %}

{% block body %}
        <h1>Add task</h1>    
        <ul>
            {% for todolist in todolist %}
                <li>{{ todolist }}  </li>
            {% empty %}
                 <li>No tasks </li>
            {% endfor %}
        </ul>
        <a href="{% url 'todolist:add' %}"> Add a New Task</a>
{% endblock %}

todolist/templates/todolist/layout.html
<!DOCTYPE html>
<html lang="en">
    
    <head>
        <title>To do list</title>
        
    </head>
    
    <body>
            {% block body %}
            {% endblock %}
    </body>
    
    

</html>